
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports: ["8000:8000"]
    env_file: [.env]
    depends_on: []
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
