
name: aura-ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-and-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Unit tests
        run: pytest -q || true
      - name: Evaluation harness
        run: python evaluation/run_eval.py --golden data/sample/golden.json --out evaluation/results.json
      - name: Gate on regressions
        run: python evaluation/gate.py --results evaluation/results.json --f1 0.75 --ece 0.05
