name: aura-quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps (pkg + hooks + tests)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pre-commit pytest

      - name: Run pre-commit (black/ruff/isort)
        run: pre-commit run --all-files

      - name: Run tests
        run: pytest -q
