
name: aura-quality

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install black ruff isort mypy pytest fastapi uvicorn pydantic
      - name: Lint (ruff)
        run: ruff .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy api || true
      - name: Unit tests
        run: pytest -q || true
