name: aura-quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install "ruff==0.6.9" "black==24.8.0" "isort==5.13.2" "mypy==1.10.0" "pytest==8.2.0"

      - name: Lint (ruff)
        run: ruff check . --output-format=github

      - name: Format check (black)
        run: black --check .

      - name: Import order check (isort)
        run: isort . --check-only

      - name: Type check (mypy)
        run: mypy api || true

      - name: Unit tests
        run: pytest -q || true
